name: Build and publish

on:
  release:
    types: [ created ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number to build'
        required: true
        default: '3.8.1'


jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - name: Version
        id: version
        run: |
          if [ ${{ github.ref_name }} == master ]; then
            echo "version=test" >> "$GITHUB_OUTPUT"
            exit -1
          else
            echo "version=${{ github.ref_name }}" >> "$GITHUB_OUTPUT"
          fi
    outputs:
      version: ${{ steps.version.outputs.version}}

  build:
    needs: check
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Hello ${{ needs.check.outputs.version }}
        run: |
          mkdir installer
          npm run inst
          npm run build
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: installer/FontMassivePack.exe
          tag: ${{ needs.check.outputs.version }}
          overwrite: true
          file_glob: true