name: Build and publish

on:
    push:
        tags:
            - "*"

jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
      - run: mkdir installer
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm run test
          npm run build
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.TOKEN_A }}
          file: installer/FontMassivePack.exe
          asset_name: FontMassivePack.exe
          tag: ${{ github.ref }}