name: Build and publish

on:
  push:
    tags:
      - "*"
  release:
    types: [ created ]
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: mkdir installer
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: [20.x]

      - name: Build
        run: |
          npm run test
          npm run build
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: installer/FontMassivePack.exe
          tag: ${{ github.ref_name }}
          overwrite: true
          file_glob: true
          