name: Build and publish

on:
  push:
    tags:
      - "*"
  release:
    types: [ created ]
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: actions/checkout@v4
    - name: Using Node.js ${{ matrix.node-version }} Windows
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build
      run: |
        npm run test
        npm run build
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: installer/FontMassivePack.exe
        tag: ${{ github.ref_name }}
        overwrite: true
        file_glob: true
          